"""DO NOT EDIT — generated by ``scripts/generate_taxonomy_constants.py``.

Source of truth: ``db/seeds/case_taxonomy.yaml``.
Regenerate after editing the YAML:

    python -m scripts.generate_taxonomy_constants

CI (``tests/test_taxonomy_constants_drift.py``) fails on drift.
"""

from __future__ import annotations

from typing import Final, Literal

TAXONOMY_VERSION: Final[str] = "2026-05-27-v1"

# ----- Supergroup codes -----
SupergroupCode = Literal[
    "SG_BILLING_DISPUTE",
    "SG_BLOCK_AVAILABILITY",
    "SG_BLOCK_COMPLIANCE",
    "SG_BLOCK_CREDIT",
    "SG_BLOCK_LOGISTICS",
    "SG_BLOCK_MASTER_DATA",
    "SG_BLOCK_ORDER_INTEGRITY",
    "SG_BLOCK_PRICING",
    "SG_BLOCK_UNMAPPED",
    "SG_COMPLAINT_PRODUCT",
    "SG_COMPLAINT_SERVICE",
    "SG_DOCUMENTATION",
    "SG_EDI_ESCALATION",
    "SG_LOGISTICS_CHANGE",
    "SG_NEEDS_TRIAGE",
    "SG_NEW_ORDER",
    "SG_ORDER_CHANGE",
    "SG_ORDER_STATUS_INQUIRY",
    "SG_RETURN_RGA",
    "SG_SHIPMENT_DISCREPANCY",
]

SUPERGROUP_CODES: Final[tuple[SupergroupCode, ...]] = (
    "SG_BILLING_DISPUTE",
    "SG_BLOCK_AVAILABILITY",
    "SG_BLOCK_COMPLIANCE",
    "SG_BLOCK_CREDIT",
    "SG_BLOCK_LOGISTICS",
    "SG_BLOCK_MASTER_DATA",
    "SG_BLOCK_ORDER_INTEGRITY",
    "SG_BLOCK_PRICING",
    "SG_BLOCK_UNMAPPED",
    "SG_COMPLAINT_PRODUCT",
    "SG_COMPLAINT_SERVICE",
    "SG_DOCUMENTATION",
    "SG_EDI_ESCALATION",
    "SG_LOGISTICS_CHANGE",
    "SG_NEEDS_TRIAGE",
    "SG_NEW_ORDER",
    "SG_ORDER_CHANGE",
    "SG_ORDER_STATUS_INQUIRY",
    "SG_RETURN_RGA",
    "SG_SHIPMENT_DISCREPANCY",
)

SUPERGROUPS_BY_ORIGIN: Final[dict[str, tuple[SupergroupCode, ...]]] = {
    "API": (
        "SG_BLOCK_AVAILABILITY",
        "SG_BLOCK_COMPLIANCE",
        "SG_BLOCK_CREDIT",
        "SG_BLOCK_LOGISTICS",
        "SG_BLOCK_MASTER_DATA",
        "SG_BLOCK_ORDER_INTEGRITY",
        "SG_BLOCK_PRICING",
        "SG_BLOCK_UNMAPPED",
    ),
    "CUSTOMER": (
        "SG_BILLING_DISPUTE",
        "SG_COMPLAINT_PRODUCT",
        "SG_COMPLAINT_SERVICE",
        "SG_DOCUMENTATION",
        "SG_EDI_ESCALATION",
        "SG_LOGISTICS_CHANGE",
        "SG_NEEDS_TRIAGE",
        "SG_NEW_ORDER",
        "SG_ORDER_CHANGE",
        "SG_ORDER_STATUS_INQUIRY",
        "SG_RETURN_RGA",
        "SG_SHIPMENT_DISCREPANCY",
    ),
}

# ----- Intent (leaf) codes -----
IntentCode = Literal[
    "INT_BACK_ORDER",
    "INT_BROKEN_PALLET",
    "INT_CONTRACTUAL_CORRECTION",
    "INT_CREDIT_BLOCK",
    "INT_DELIVERY_DELAY",
    "INT_DUPLICATE_PO",
    "INT_EDI_MISMATCH",
    "INT_MANUAL_ORDER_INTAKE",
    "INT_MASS_PRICING_ERROR",
    "INT_MIN_ORDER_QTY",
    "INT_OVER_MAX",
    "INT_PALLET_CONFIG",
    "INT_PRICE_HOLD_RELEASE",
    "INT_PRICE_MISMATCH",
    "INT_UNKNOWN",
    "INT_UNMAPPED_PENDING_TAXONOMY",
]

INTENT_CODES: Final[tuple[IntentCode, ...]] = (
    "INT_BACK_ORDER",
    "INT_BROKEN_PALLET",
    "INT_CONTRACTUAL_CORRECTION",
    "INT_CREDIT_BLOCK",
    "INT_DELIVERY_DELAY",
    "INT_DUPLICATE_PO",
    "INT_EDI_MISMATCH",
    "INT_MANUAL_ORDER_INTAKE",
    "INT_MASS_PRICING_ERROR",
    "INT_MIN_ORDER_QTY",
    "INT_OVER_MAX",
    "INT_PALLET_CONFIG",
    "INT_PRICE_HOLD_RELEASE",
    "INT_PRICE_MISMATCH",
    "INT_UNKNOWN",
    "INT_UNMAPPED_PENDING_TAXONOMY",
)

INTENTS_BY_SUPERGROUP: Final[dict[SupergroupCode, tuple[IntentCode, ...]]] = {
    "SG_BLOCK_AVAILABILITY": (
        "INT_BACK_ORDER",
        "INT_MIN_ORDER_QTY",
        "INT_OVER_MAX",
    ),
    "SG_BLOCK_CREDIT": (
        "INT_CREDIT_BLOCK",
    ),
    "SG_BLOCK_LOGISTICS": (
        "INT_BROKEN_PALLET",
        "INT_DELIVERY_DELAY",
        "INT_PALLET_CONFIG",
    ),
    "SG_BLOCK_ORDER_INTEGRITY": (
        "INT_CONTRACTUAL_CORRECTION",
        "INT_DUPLICATE_PO",
        "INT_EDI_MISMATCH",
    ),
    "SG_BLOCK_PRICING": (
        "INT_MASS_PRICING_ERROR",
        "INT_PRICE_HOLD_RELEASE",
        "INT_PRICE_MISMATCH",
    ),
    "SG_BLOCK_UNMAPPED": (
        "INT_UNMAPPED_PENDING_TAXONOMY",
    ),
    "SG_NEEDS_TRIAGE": (
        "INT_UNKNOWN",
    ),
    "SG_NEW_ORDER": (
        "INT_MANUAL_ORDER_INTAKE",
    ),
}

# ----- SAP block-code mapping -----
# Key: (sap_block_code, sap_sales_org-or-empty). Empty sales_org = global.
SAP_BLOCK_TO_INTENT: Final[dict[tuple[str, str], IntentCode]] = {
}

# ----- Reserved sentinel codes (referenced by app logic) -----
SG_NEEDS_TRIAGE: Final[SupergroupCode] = "SG_NEEDS_TRIAGE"
SG_BLOCK_UNMAPPED: Final[SupergroupCode] = "SG_BLOCK_UNMAPPED"
INT_UNMAPPED_PENDING_TAXONOMY: Final[IntentCode] = "INT_UNMAPPED_PENDING_TAXONOMY"
INT_UNKNOWN: Final[IntentCode] = "INT_UNKNOWN"
