from __future__ import annotations

# Phase 2 — Compliance Shadow
#
# Responsibilities:
#   audit()   — call the constrained backend, return ComplianceDecision
#               (status constrained to GREEN|YELLOW|RED, TraceID auto-set,
#                reasons and policy_hits captured)
#   enforce() — translate ComplianceDecision into a typed ShadowEnforcement
#               routing action without touching any recipe or execution logic:
#                 GREEN  → PROCEED
#                 YELLOW → ESCALATE  (caller routes to MANUAL_REVIEW_REQUIRED)
#                 RED    → BLOCK     (caller halts; explanation attached)
#
# Invariants:
#   - No recipe is selected or called here
#   - No graph state is mutated here
#   - Shadow verdict is constrained at generation time via the backend
#     (DeterministicFallbackBackend by default, OutlinesConstrainedBackend
#      when injected via USE_OUTLINES_BACKEND=1 or direct injection)
#   - Remote serving (vLLM endpoint) is NOT implemented here (Phase 2 scope)

import abc
import logging

from contracts.models import ComplianceDecision, GraphState, ShadowEnforcement, ShadowStatus
from constraints import get_constrained_backend

logger = logging.getLogger("asoe.compliance")

# Enforcement routing table: status → (action, description, log level).
# The description is appended to the standard prefix
# "Compliance Shadow returned {status}." to form the explanation string.
# For non-GREEN verdicts, the decision reasons are also appended.
_ENFORCE_TABLE: dict[ShadowStatus, tuple[str, str, int]] = {
    ShadowStatus.RED: ("BLOCK", "Execution halted.", logging.WARNING),
    ShadowStatus.YELLOW: ("ESCALATE", "Routing to MANUAL_REVIEW_REQUIRED.", logging.WARNING),
    ShadowStatus.GREEN: ("PROCEED", "Auto-proceed is allowed.", logging.INFO),
}


# ---------------------------------------------------------------------------
# Formal interface (tasks.md §2.1 "define a ComplianceShadow interface")
# ---------------------------------------------------------------------------

class ComplianceShadowBase(abc.ABC):
    """Abstract interface every ComplianceShadow implementation must satisfy."""

    @abc.abstractmethod
    def audit(self, state: GraphState) -> ComplianceDecision:
        """Produce a constrained ComplianceDecision for *state*.

        Must include: status (GREEN|YELLOW|RED), trace_id, reasons, policy_hits.
        Must NOT select or call any recipe.
        """

    @abc.abstractmethod
    def enforce(self, decision: ComplianceDecision) -> ShadowEnforcement:
        """Translate a ComplianceDecision into a typed routing action.

        GREEN  → PROCEED
        YELLOW → ESCALATE
        RED    → BLOCK

        Must NOT execute any recipe or mutate state.
        """


# ---------------------------------------------------------------------------
# Concrete implementation
# ---------------------------------------------------------------------------

class ComplianceShadow(ComplianceShadowBase):
    """Compliance Shadow backed by a constrained-generation backend.

    Args:
        backend: Injectable constrained backend.  Defaults to the env-driven
                 router (DeterministicFallbackBackend or OutlinesConstrainedBackend).
    """

    def __init__(self, backend=None) -> None:
        self.backend = backend if backend is not None else get_constrained_backend()

    # ------------------------------------------------------------------
    # audit — Phase 2.1
    # ------------------------------------------------------------------

    def audit(self, state: GraphState) -> ComplianceDecision:
        """Call the constrained backend and return a typed ComplianceDecision.

        The backend constrains the verdict to GREEN|YELLOW|RED at generation
        time (Guidance / Outlines pattern).  TraceID is auto-generated by the
        ComplianceDecision model.
        """
        # All backends accept the full GraphState — see the unified
        # signature contract on DeterministicFallbackBackend /
        # OutlinesConstrainedBackend / AnthropicBackend.
        raw = self.backend.shadow_decision(state)
        constrained_by = type(self.backend).__name__

        decision = ComplianceDecision(
            status=ShadowStatus(raw.status),
            reasons=raw.reasons,
            policy_hits=raw.policy_hits,
            constrained_by=constrained_by,
        )
        logger.info(
            "shadow_audit",
            extra={
                "trace_id": decision.trace_id,
                "status": decision.status.value,
                "reasons": decision.reasons,
                "policy_hits": decision.policy_hits,
                "constrained_by": decision.constrained_by,
            },
        )
        return decision

    # ------------------------------------------------------------------
    # enforce — Phase 2.2
    # ------------------------------------------------------------------

    def enforce(self, decision: ComplianceDecision) -> ShadowEnforcement:
        """Return the routing action for *decision* — no recipe, no mutation.

        GREEN  → PROCEED   ("auto-proceed is allowed")
        YELLOW → ESCALATE  ("route to MANUAL_REVIEW_REQUIRED")
        RED    → BLOCK     ("halt immediately; explain compliance breach")
        """
        action, description, level = _ENFORCE_TABLE[decision.status]

        explanation = f"Compliance Shadow returned {decision.status.value}. {description}"
        if decision.status != ShadowStatus.GREEN and decision.reasons:
            explanation += " " + "; ".join(decision.reasons)

        enforcement = ShadowEnforcement(
            action=action,
            trace_id=decision.trace_id,
            explanation=explanation,
        )
        logger.log(
            level,
            "shadow_enforce",
            extra={
                "trace_id": enforcement.trace_id,
                "action": enforcement.action,
                "source_status": decision.status.value,
            },
        )
        return enforcement
