from __future__ import annotations

# Phase 2 — Compliance Shadow
#
# Responsibilities:
#   audit()   — call the constrained backend, return ComplianceDecision
#               (status constrained to GREEN|YELLOW|RED, TraceID auto-set,
#                reasons and policy_hits captured)
#   enforce() — translate ComplianceDecision into a typed ShadowEnforcement
#               routing action without touching any recipe or execution logic:
#                 GREEN  → PROCEED
#                 YELLOW → ESCALATE  (caller routes to MANUAL_REVIEW_REQUIRED)
#                 RED    → BLOCK     (caller halts; explanation attached)
#
# Invariants:
#   - No recipe is selected or called here
#   - No graph state is mutated here
#   - Shadow verdict is constrained at generation time via the backend
#     (DeterministicFallbackBackend by default, OutlinesConstrainedBackend
#      when injected via USE_OUTLINES_BACKEND=1 or direct injection)
#   - Remote serving (vLLM endpoint) is NOT implemented here (Phase 2 scope)

import abc
import logging

from contracts.models import ComplianceDecision, GraphState, ShadowEnforcement, ShadowStatus
from constraints import get_constrained_backend

logger = logging.getLogger("asoe.compliance")


# ---------------------------------------------------------------------------
# Formal interface (tasks.md §2.1 "define a ComplianceShadow interface")
# ---------------------------------------------------------------------------

class ComplianceShadowBase(abc.ABC):
    """Abstract interface every ComplianceShadow implementation must satisfy."""

    @abc.abstractmethod
    def audit(self, state: GraphState) -> ComplianceDecision:
        """Produce a constrained ComplianceDecision for *state*.

        Must include: status (GREEN|YELLOW|RED), trace_id, reasons, policy_hits.
        Must NOT select or call any recipe.
        """

    @abc.abstractmethod
    def enforce(self, decision: ComplianceDecision) -> ShadowEnforcement:
        """Translate a ComplianceDecision into a typed routing action.

        GREEN  → PROCEED
        YELLOW → ESCALATE
        RED    → BLOCK

        Must NOT execute any recipe or mutate state.
        """


# ---------------------------------------------------------------------------
# Concrete implementation
# ---------------------------------------------------------------------------

class ComplianceShadow(ComplianceShadowBase):
    """Compliance Shadow backed by a constrained-generation backend.

    Args:
        backend: Injectable constrained backend.  Defaults to the env-driven
                 router (DeterministicFallbackBackend or OutlinesConstrainedBackend).
    """

    def __init__(self, backend=None) -> None:
        self.backend = backend if backend is not None else get_constrained_backend()

    # ------------------------------------------------------------------
    # audit — Phase 2.1
    # ------------------------------------------------------------------

    def audit(self, state: GraphState) -> ComplianceDecision:
        """Call the constrained backend and return a typed ComplianceDecision.

        The backend constrains the verdict to GREEN|YELLOW|RED at generation
        time (Guidance / Outlines pattern).  TraceID is auto-generated by the
        ComplianceDecision model.
        """
        if hasattr(self.backend, "shadow_prompt"):
            # Outlines path: backend expects a prompt string
            raw = self.backend.shadow_decision(self.backend.shadow_prompt(state))
            constrained_by = "Guidance/Outlines schema"
        else:
            # Fallback path: backend accepts the full GraphState
            raw = self.backend.shadow_decision(state)
            constrained_by = "Guidance/Outlines fallback schema"

        decision = ComplianceDecision(
            status=ShadowStatus(raw.status),
            reasons=raw.reasons,
            policy_hits=raw.policy_hits,
            constrained_by=constrained_by,
        )
        logger.info(
            "shadow_audit",
            extra={
                "trace_id": decision.trace_id,
                "status": decision.status.value,
                "reasons": decision.reasons,
                "policy_hits": decision.policy_hits,
                "constrained_by": decision.constrained_by,
            },
        )
        return decision

    # ------------------------------------------------------------------
    # enforce — Phase 2.2
    # ------------------------------------------------------------------

    def enforce(self, decision: ComplianceDecision) -> ShadowEnforcement:
        """Return the routing action for *decision* — no recipe, no mutation.

        GREEN  → PROCEED   ("auto-proceed is allowed")
        YELLOW → ESCALATE  ("route to MANUAL_REVIEW_REQUIRED")
        RED    → BLOCK     ("halt immediately; explain compliance breach")
        """
        if decision.status == ShadowStatus.RED:
            explanation = (
                "Compliance Shadow returned RED. "
                "Execution halted. "
                + "; ".join(decision.reasons)
            )
            enforcement = ShadowEnforcement(
                action="BLOCK",
                trace_id=decision.trace_id,
                explanation=explanation,
            )
            logger.warning(
                "shadow_enforce",
                extra={
                    "trace_id": enforcement.trace_id,
                    "action": enforcement.action,
                    "source_status": decision.status.value,
                },
            )
            return enforcement

        if decision.status == ShadowStatus.YELLOW:
            explanation = (
                "Compliance Shadow returned YELLOW. "
                "Routing to MANUAL_REVIEW_REQUIRED. "
                + "; ".join(decision.reasons)
            )
            enforcement = ShadowEnforcement(
                action="ESCALATE",
                trace_id=decision.trace_id,
                explanation=explanation,
            )
            logger.warning(
                "shadow_enforce",
                extra={
                    "trace_id": enforcement.trace_id,
                    "action": enforcement.action,
                    "source_status": decision.status.value,
                },
            )
            return enforcement

        # GREEN
        enforcement = ShadowEnforcement(
            action="PROCEED",
            trace_id=decision.trace_id,
            explanation="Compliance Shadow returned GREEN. Auto-proceed is allowed.",
        )
        logger.info(
            "shadow_enforce",
            extra={
                "trace_id": enforcement.trace_id,
                "action": enforcement.action,
                "source_status": decision.status.value,
            },
        )
        return enforcement
