"""Generate Python and TypeScript constants from the taxonomy YAML.

The YAML at ``db/seeds/case_taxonomy.yaml`` is the single source of truth
(decision D1). This script projects it into two **committed** files:

  - ``contracts/_generated/taxonomy_constants.py``
  - ``asoe-ui/src/generated/taxonomy.ts``

CI runs ``--check`` to fail the build if the generated files drift from
the YAML. Steward changes follow §9.1 of the requirements: edit YAML,
regenerate, PR, review.

Output is fully deterministic: sorted, identically-formatted on every
run. The drift test (tests/test_taxonomy_constants_drift.py) relies on
byte-stable output.

Usage:
    python -m scripts.generate_taxonomy_constants            # write files
    python -m scripts.generate_taxonomy_constants --check    # CI guard
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from scripts.seed_taxonomy import REPO_ROOT, load_yaml

PY_OUT = REPO_ROOT / "contracts" / "_generated" / "taxonomy_constants.py"
TS_OUT = REPO_ROOT / "asoe-ui" / "src" / "generated" / "taxonomy.ts"

_GENERATED_HEADER_PY = '''"""DO NOT EDIT — generated by ``scripts/generate_taxonomy_constants.py``.

Source of truth: ``db/seeds/case_taxonomy.yaml``.
Regenerate after editing the YAML:

    python -m scripts.generate_taxonomy_constants

CI (``tests/test_taxonomy_constants_drift.py``) fails on drift.
"""
'''

_GENERATED_HEADER_TS = """// DO NOT EDIT — generated by scripts/generate_taxonomy_constants.py.
//
// Source of truth: db/seeds/case_taxonomy.yaml.
// Regenerate after editing the YAML:
//
//     python -m scripts.generate_taxonomy_constants
//
// CI (tests/test_taxonomy_constants_drift.py) fails on drift.
"""


def _render_python(data: dict) -> str:
    sg_codes = sorted(row["code"] for row in data["supergroups"])
    int_codes = sorted(row["code"] for row in data["intents"])

    sg_by_origin: dict[str, list[str]] = {"CUSTOMER": [], "API": [], "BOTH": []}
    for row in data["supergroups"]:
        sg_by_origin[row["origin"]].append(row["code"])
    for codes in sg_by_origin.values():
        codes.sort()

    intents_by_supergroup: dict[str, list[str]] = {}
    for row in data["intents"]:
        intents_by_supergroup.setdefault(row["supergroup_code"], []).append(row["code"])
    for sg in intents_by_supergroup:
        intents_by_supergroup[sg].sort()

    sap_block_to_intent: dict[tuple[str, str], str] = {}
    for row in data["intents"]:
        sbc = row.get("sap_block_code")
        if sbc:
            org = row.get("sap_sales_org") or ""
            sap_block_to_intent[(sbc, org)] = row["code"]

    lines: list[str] = []
    lines.append(_GENERATED_HEADER_PY)
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Final, Literal")
    lines.append("")
    lines.append(f'TAXONOMY_VERSION: Final[str] = "{data["version"]}"')
    lines.append("")
    lines.append("# ----- Supergroup codes -----")
    lines.append("SupergroupCode = Literal[")
    for code in sg_codes:
        lines.append(f'    "{code}",')
    lines.append("]")
    lines.append("")
    lines.append("SUPERGROUP_CODES: Final[tuple[SupergroupCode, ...]] = (")
    for code in sg_codes:
        lines.append(f'    "{code}",')
    lines.append(")")
    lines.append("")
    lines.append("SUPERGROUPS_BY_ORIGIN: Final[dict[str, tuple[SupergroupCode, ...]]] = {")
    for origin in sorted(sg_by_origin):
        codes = sg_by_origin[origin]
        if not codes:
            continue
        lines.append(f'    "{origin}": (')
        for code in codes:
            lines.append(f'        "{code}",')
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("# ----- Intent (leaf) codes -----")
    lines.append("IntentCode = Literal[")
    for code in int_codes:
        lines.append(f'    "{code}",')
    lines.append("]")
    lines.append("")
    lines.append("INTENT_CODES: Final[tuple[IntentCode, ...]] = (")
    for code in int_codes:
        lines.append(f'    "{code}",')
    lines.append(")")
    lines.append("")
    lines.append("INTENTS_BY_SUPERGROUP: Final[dict[SupergroupCode, tuple[IntentCode, ...]]] = {")
    for sg in sorted(intents_by_supergroup):
        lines.append(f'    "{sg}": (')
        for code in intents_by_supergroup[sg]:
            lines.append(f'        "{code}",')
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("# ----- SAP block-code mapping -----")
    lines.append("# Key: (sap_block_code, sap_sales_org-or-empty). Empty sales_org = global.")
    lines.append("SAP_BLOCK_TO_INTENT: Final[dict[tuple[str, str], IntentCode]] = {")
    for (sbc, org), int_code in sorted(sap_block_to_intent.items()):
        lines.append(f'    ("{sbc}", "{org}"): "{int_code}",')
    lines.append("}")
    lines.append("")
    lines.append("# ----- Reserved sentinel codes (referenced by app logic) -----")
    lines.append('SG_NEEDS_TRIAGE: Final[SupergroupCode] = "SG_NEEDS_TRIAGE"')
    lines.append('SG_BLOCK_UNMAPPED: Final[SupergroupCode] = "SG_BLOCK_UNMAPPED"')
    lines.append('INT_UNMAPPED_PENDING_TAXONOMY: Final[IntentCode] = "INT_UNMAPPED_PENDING_TAXONOMY"')
    lines.append('INT_UNKNOWN: Final[IntentCode] = "INT_UNKNOWN"')
    lines.append("")
    return "\n".join(lines)


def _render_typescript(data: dict) -> str:
    sg_codes = sorted(row["code"] for row in data["supergroups"])
    int_codes = sorted(row["code"] for row in data["intents"])

    sg_by_origin: dict[str, list[str]] = {"CUSTOMER": [], "API": [], "BOTH": []}
    for row in data["supergroups"]:
        sg_by_origin[row["origin"]].append(row["code"])
    for codes in sg_by_origin.values():
        codes.sort()

    intents_by_supergroup: dict[str, list[str]] = {}
    for row in data["intents"]:
        intents_by_supergroup.setdefault(row["supergroup_code"], []).append(row["code"])
    for sg in intents_by_supergroup:
        intents_by_supergroup[sg].sort()

    lines: list[str] = [_GENERATED_HEADER_TS]
    lines.append(f'export const TAXONOMY_VERSION = "{data["version"]}" as const;')
    lines.append("")
    lines.append("// ----- Supergroup codes -----")
    lines.append("export type SupergroupCode =")
    for i, code in enumerate(sg_codes):
        prefix = "  | " if i > 0 else "    "
        suffix = ";" if i == len(sg_codes) - 1 else ""
        lines.append(f'{prefix}"{code}"{suffix}')
    lines.append("")
    lines.append("export const SUPERGROUP_CODES: readonly SupergroupCode[] = [")
    for code in sg_codes:
        lines.append(f'  "{code}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export const SUPERGROUPS_BY_ORIGIN: Readonly<Record<string, readonly SupergroupCode[]>> = {")
    for origin in sorted(sg_by_origin):
        codes = sg_by_origin[origin]
        if not codes:
            continue
        items = ", ".join(f'"{c}"' for c in codes)
        lines.append(f'  {origin}: [{items}],')
    lines.append("};")
    lines.append("")
    lines.append("// ----- Intent (leaf) codes -----")
    lines.append("export type IntentCode =")
    for i, code in enumerate(int_codes):
        suffix = ";" if i == len(int_codes) - 1 else ""
        sep = "  |" if i > 0 else "    "
        lines.append(f'  {sep} "{code}"{suffix}')
    lines.append("")
    lines.append("export const INTENT_CODES: readonly IntentCode[] = [")
    for code in int_codes:
        lines.append(f'  "{code}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export const INTENTS_BY_SUPERGROUP: Readonly<Record<SupergroupCode, readonly IntentCode[]>> = {")
    for sg in sorted(intents_by_supergroup):
        items = ", ".join(f'"{c}"' for c in intents_by_supergroup[sg])
        lines.append(f'  {sg}: [{items}],')
    # Any supergroups without intents render as empty arrays for type completeness.
    for sg in sg_codes:
        if sg not in intents_by_supergroup:
            lines.append(f"  {sg}: [],")
    lines.append("} as const;")
    lines.append("")
    lines.append("// ----- Reserved sentinel codes -----")
    lines.append('export const SG_NEEDS_TRIAGE: SupergroupCode = "SG_NEEDS_TRIAGE";')
    lines.append('export const SG_BLOCK_UNMAPPED: SupergroupCode = "SG_BLOCK_UNMAPPED";')
    lines.append('export const INT_UNMAPPED_PENDING_TAXONOMY: IntentCode = "INT_UNMAPPED_PENDING_TAXONOMY";')
    lines.append('export const INT_UNKNOWN: IntentCode = "INT_UNKNOWN";')
    lines.append("")
    return "\n".join(lines)


def generate() -> tuple[str, str]:
    """Pure function: YAML -> (python_text, typescript_text)."""
    data = load_yaml()
    return _render_python(data), _render_typescript(data)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if regenerated content differs from committed files.",
    )
    args = parser.parse_args(argv)

    py_text, ts_text = generate()

    # Binary I/O so newline handling is identical across platforms — text-
    # mode write on Windows turns ``\n`` into ``\r\n`` and text-mode read
    # turns it back, hiding a real drift in the committed file (code-
    # review finding #1, BLOCKER).
    py_bytes = py_text.encode("utf-8")
    ts_bytes = ts_text.encode("utf-8")

    if args.check:
        existing_py = PY_OUT.read_bytes() if PY_OUT.exists() else b""
        existing_ts = TS_OUT.read_bytes() if TS_OUT.exists() else b""
        ok = True
        if existing_py != py_bytes:
            print(f"[drift] {PY_OUT.relative_to(REPO_ROOT)} is out of date", file=sys.stderr)
            ok = False
        if existing_ts != ts_bytes:
            print(f"[drift] {TS_OUT.relative_to(REPO_ROOT)} is out of date", file=sys.stderr)
            ok = False
        if not ok:
            print(
                "Run `python -m scripts.generate_taxonomy_constants` and commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_bytes(py_bytes)
    TS_OUT.write_bytes(ts_bytes)
    print(f"wrote {PY_OUT.relative_to(REPO_ROOT)}")
    print(f"wrote {TS_OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
